sudo: false
language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master
ruby:
  - 2.3.3
before_install: gem install bundler -v 1.16.0

install:
  - go get -t -v ./...

script:
  - make test

matrix:
  allow_failures:
    - go: master
  fast_finish: true
